# 列表如何转为ndarray

In [2]:
#列表转ndarray
import numpy as np

list1 = [1, 2, 3, 4]
print(list1)
print(type(list1))


[1, 2, 3, 4]
<class 'list'>


In [2]:
oneArray = np.array(list1)
print(type(oneArray))  #类型是ndarray
print(oneArray)# 没有逗号分隔

<class 'numpy.ndarray'>
[1 2 3 4]


# ndarray与Python原生list运算效率对比

In [3]:
import random
import time
import numpy as np

#随机1亿个数据
a = []
for i in range(100000000):
    a.append(random.random())
print('随机完毕')

随机完毕


In [5]:
b = np.array(a)  # 转换为ndarray
print('转换完毕')

转换完毕


In [6]:
#ndarray的计算效率优于python的list
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

0.892327070236206 0.18476605415344238


In [7]:
t1 = np.array([1, 2, 3])
print(t1)
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
print(type(range(10)))  # range返回的是一个range对象，不能直接转换为ndarray
t2 = np.array(range(10))
print(t2)
print(type(t2))

<class 'range'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [9]:
t3 = np.arange(0, 10, 2)  # 等价于range(0,10,2),返回ndarray
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [10]:
#二维列表转ndarray

list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)
print(list2)  #列表的输出是有逗号的，ndarray的输出是没有逗号的

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


In [11]:
twoArray.tolist()  # ndarray转换为列表

[[1, 2], [3, 4], [5, 6]]

# 4.3 常用属性

In [3]:
#看ndarray的各种属性
list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像) 
print(twoArray.ndim)

# 形状（行，列） (0 axis,1 axis)
print(twoArray.shape)

# 有多少个元素
print(twoArray.size)
# 数据类型
print(twoArray.dtype)  #默认int32,4个字节，数据范围 -21亿到21亿

2
(3, 2)
6
int64


# 4.4 调整数组的形状

In [4]:
four = np.array([[1, 2, 3], [4, 5, 6]])

print(four)
# 修改的是原有的
four1 = four
print(id(four))

[[1 2 3]
 [4 5 6]]
1993660068944


In [5]:
four.shape = (3, 2)  # 改变形状
print(id(four))
print(id(four1))# twoArray的id与four的id相同，说明修改的是原有的
print(four)

1993660068944
1993660068944
[[1 2]
 [3 4]
 [5 6]]


In [6]:
print('-' * 50)
# 返回一个新的数组，reshape后id和之前的不一样
four2 = four.reshape(2, 3)
print(four)
print(id(four))
print(id(four2))
four2

--------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
1993660068944
1993153582192


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# 将多维变成一维数组
five = four.reshape((6,), order='F')
print(five)
five = four.reshape((6,), order='C')  # 与reshape(2,3)相同
print(five)
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten()  # 展开成一维数组
print(five)
print('-' * 50)
print(six)

# print(five.reshape(3,2))

[1 3 5 2 4 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
--------------------------------------------------
[1 2 3 4 5 6]


In [12]:
seven = five.reshape(3, 2)  # 改变形状
seven

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
print('-' * 50)
# 拓展：数组的形状
t = np.arange(24)  #和列表的range函数一样，生成一个数组
print(t)
print(f'shape{t.shape}')
print(t.ndim) # 维度
 # 转换成二维
t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)

--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape(24,)
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [15]:
print(t1.shape)
# 转成三维
#最前面的是零轴，轴越小，越靠外，最小的轴是最外层
# 0轴，1轴，2轴
t2 = t.reshape((2, 3, 4))
print(t2)
print(t2.shape)
print(t2.ndim)

(4, 6)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [16]:
t3 = t.reshape((2, 3, 2, 2))
print(t3)
print(t3.shape)
print(t3.ndim)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
(2, 3, 2, 2)
4


# 4.5 数组转换为列表

In [20]:
#将数组转换为列表 tolist
a = np.array([9, 12, 88, 14, 25])
print(type(a))
list_a = a.tolist()
print(list_a)
print(type(list_a))


<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


# 5 NumPy的数据类型

In [21]:
import random

f = np.array([1, 2, 3, 4, 127], dtype=np.int8)  # 返回数组中每个元素的字节单位长度,dtype设置数据类型

print(f.itemsize)  # 1字节 
# 1 np.int16(一个字节) 2 np.int32(两个字节) 4 np.int64(四个字节)
# 获取数据类型
print(f.dtype)


1
int8


In [22]:
f[4] = f[4] + 1  #溢出

C:\Users\zzk\AppData\Local\Temp\ipykernel_32112\827682908.py:1: RuntimeWarning: overflow encountered in scalar add
  f[4] = f[4] + 1  #溢出


In [23]:
f[4]

np.int8(-128)

In [24]:
# 调整数据类型
f1 = f.astype(np.int64) # 转换为int64类型
print(f1.dtype) #显示数据类型
print(f1.itemsize)  #显示字节数
print('-' * 50)

int64
8
--------------------------------------------------


In [25]:
random.random()  # 随机生成0-1之间的小数

0.9172984506371463

In [27]:
# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(), 2))
# np.float16 半精度
arr = np.array([random.random() for i in range(10)])
print(arr)
print(arr.itemsize)
print(arr.dtype)
# 取小数点后两位
print(np.round(arr, 2))

0.73
[0.78054281 0.68774241 0.73226113 0.22123356 0.24428109 0.00977916
 0.18034334 0.31061159 0.82650602 0.3467124 ]
8
float64
[0.78 0.69 0.73 0.22 0.24 0.01 0.18 0.31 0.83 0.35]


# 数组和数的计算

In [28]:
# [1,2,3]+5  # 不能直接加，会报错

TypeError: can only concatenate list (not "int") to list

In [29]:
# 由于numpy的广播机机制在运算过程中，加减乘除的值被广播到所有的元素上面
t1 = np.arange(24).reshape((6, 4))
print(t1)
print("-" * 20)
t2 = t1.tolist()
print(t1 + 2)
# print(t2+2) 不能对列表进行直接加整数操作
print("-" * 20)
print(t1 * 2)
print("-" * 20)
print(t1 / 2)

#无论多少维的ndarray都可以直接和一个常数进行运算

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [30]:
#形状相同,才可以进行加减乘除
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((6, 4))
print(t1)
print(t2)
print('-' * 50)
print(t1 + t2)
print('-' * 50)
print(t1 * t2)  #是否是矩阵乘法？不是,是对应元素相乘


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------------------------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [31]:
#shape不同，不能进行运算
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((3, 6))
print(t1)
print(t2)
print(t1 - t2)

ValueError: cannot reshape array of size 6 into shape (3,6)

In [32]:
#一维数组和二维数组进行运算时，一维的元素个数和列数相等
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t2.shape)
print(t1)
print(t2)
t1 - t2


(1, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]


array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [33]:
(t1 - t2).shape

(4, 6)

In [34]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(4).reshape((4, 1))
print(t2)
print(t1)
t1 - t2 # 每一列减去相同的数

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20]])

In [37]:
#随机3维数组
a = np.arange(24).reshape((2, 3, 4))
print(a)
b = np.arange(12).reshape((1, 3, 4))
print(b)
a - b # 其中的元素相减 （3，4）维度相同

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]])

结论：ndim要相同，可以某一个轴的size不同，但是其中一个ndarray必须对应的轴的size为1

# 练习轴

In [38]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("-" * 20)
print(np.sum(a, axis=0))  # [5 7 9]，按哪个轴求和，哪个轴没了
print("-" * 20)
print(np.sum(a, axis=1))  # [ 6 15]
print("-" * 20)
print(np.sum(a))
print("-" * 20)


[[1 2 3]
 [4 5 6]]
--------------------
[5 7 9]
--------------------
[ 6 15]
--------------------
21
--------------------


In [40]:
a = np.arange(24).reshape((2, 3, 4))
b = np.sum(a, axis=0)
print("-" * 20)
print(b.shape)
c = np.sum(a, axis=1)
print("-" * 20)
print(c.shape)
d = np.sum(a, axis=2)
print("-" * 20)
print(d.shape)

--------------------
(3, 4)
--------------------
(2, 4)
--------------------
(2, 3)


# 索引和切片

In [41]:
import numpy as np

a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[0], a)

# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

print(a[2:8:2])  #切片是左闭右开 从索引 2 开始到索引 8 停止，间隔为 2

0 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]


In [42]:
import numpy as np

t1 = np.arange(24).reshape(4, 6)
print(t1)
print('*' * 20)
print(t1[1])  # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*' * 20)
print(t1[1:])  # 取连续的多行
print('*' * 20)
print(t1[1:3, :])  # 取连续的多行
print('*' * 20)
print(t1[[0, 2, 3]])  # 取不连续的多行

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [43]:
#看列表
t2 = np.arange(24).reshape(4, 6).tolist()
t2[[0, 2, 3]]

TypeError: list indices must be integers or slices, not list

In [44]:
print(t1[:, 1])  # 取一列
print('*' * 20)
print(t1[:, 1:])  # 连续的多列
print('*' * 20)
print(t1[:, [0, 2, 3]])  # 取不连续的多列
print('*' * 20)
print(t1[2, 3])  # # 取某一个值,三行四列  py是t1[2][3]
print('*' * 20)
print(t1[[0, 1, 1], [0, 1, 3]])  # 取多个不连续的值，[[行，行。。。],[列，列。。。]]

t1[1:3, 1:4]  #取1-3行，1-4列

[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************
[0 7 9]


array([[ 7,  8,  9],
       [13, 14, 15]])

# 修改值

In [45]:
import numpy as np

t = np.arange(24).reshape(4, 6)
print(t)
print(id(t))
print('-' * 50)
# # 修改某一行的值
# t[1,:]=0
#
# # 修改某一列的值
# t[:,1]=0
#
# # 修改连续多行
# t[1:3,:]=0
#
# # 修改连续多列
# t[:,1:4]=0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:3,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[1,3]]=0

# 可以根据条件修改，比如讲小于10的值改掉
# t[t<10]=0

# 使用逻辑判断
# np.logical_and	& # np.logical_or	|
# np.logical_not		~
# t[(t>2)&(t<6)]=0	# 逻辑与，and
# t[(t<2)|(t>6)]=0	# 逻辑或，or
# t[~(t>6)]=0	# 逻辑非
# print(t)
t = t.clip(10, 18)
print(id(t))
t


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
1993660624176
--------------------------------------------------
1993660625616


array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 18, 18, 18, 18, 18]])

In [46]:
t = np.arange(24).reshape(4, 6)
t < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [47]:
#python的三目运算
a = 10
b = 15
c = a if a > b else b
c

15

In [48]:
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
result = np.where(score < 80, True, False)  #类似于if else
print(result)


[[80 88]
 [82 81]
 [75 81]]
[[False False]
 [False False]
 [ True False]]


In [49]:
score[result] = 100
score

array([[ 80,  88],
       [ 82,  81],
       [100,  81]])

# 数据的添加，删除与去重

In [50]:
# 1. numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。
# 此外，输入数组的维度必须匹配否则将生成ValueError。
'''
参 数 说 明 ：                                                                                                     arr： 输 入 数 组                                                                                                 values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）                                                            axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！当axis有定义的时候，分别为0和1的时候。当
axis有定义的时候，分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。
'''
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print('第一个数组：')
print(a)
print('\n')

print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))  #ndarray会被展平
print('\n')
print(a)
print('-' * 50)


第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]]
--------------------------------------------------
